### ISSUE TITLE
No password check when DefaultTlsDirContextAuthenticationStrategy is activated

### ISSUE THREAD

**Issue by derTobsch** [spring-projects/spring-ldap#430] opened 2016-11-18 13:56 UTC
We stumbled over this problem one week ago and thought it would be nice to tell you about this. 

When the ```DefaultTlsDirContextAuthenticationStrategy``` is set as authentication strategy on the ```LdapContextSource``` **every password** will be **accepted**, because there happens no bind with user credentials against ldap.

After deep debugging into your code and a lot of searching on the web, we found this post in the spring forum from Jul 18th, 2013.
http://forum.spring.io/forum/spring-projects/data/ldap/129629-ldap-with-tls-authentication-issues

_mwebb_ describes very detailed the problem and gives an code example approach to fix this.

> It appears that SimpleDirContextAuthenticationStrategy and DefaultTlsDirContextAuthenticationStrategy are not symmetrical in their behaviour. I resolved this be creating a custom TlsDirContextAuthenticationStrategy and adding a ctx.reconnect() to the applyAuthentication(), after the environment settings for a simple bind have been set, as follows:

```java
private void applyAuthentication(LdapContext ctx, String userDn, String password) throws NamingException {
ctx.addToEnvironment(Context.SECURITY_AUTHENTICATI ON, SIMPLE_AUTHENTICATION);
ctx.addToEnvironment(Context.SECURITY_PRINCIPAL, userDn);
ctx.addToEnvironment(Context.SECURITY_CREDENTIALS, password);
// Force reconnect with user credentials
ctx.reconnect(null)
}
```

The problem he describes was exactly the same we had. The line ```ctx.reconnect(null)``` fixed it for us.

**Comment by derTobsch** [comment] 2016-11-28 07:34
No Action, No Bug?

**Comment by alex-sherwin** [comment] 2017-07-11 14:01
FWIW, I ran up against this problem this week as well.  

Lots of hair pulling as to how the `LdapTemplate.authenticate(..)` suite of functions was not actually testing the specified user/password via a bind operation.

**Comment by rwinch** [comment] 2017-09-28 20:51
Thank you for the report. Unless someone comes up with another example, I'm closing this as invalid.

Please see the explanation here https://github.com/spring-projects/spring-ldap/pull/432#issuecomment-332959893

**Closed by rwinch** 2017-09-28 20:51 UTC

**Comment by espenhw** [comment] 2017-09-29 21:40
Five minutes of playing with @derTobsch's example project shows that this is not true; the exact same thing happens with anonymous search disabled.  See my updated version here: https://github.com/espenhw/tls-bug-demo

**Comment by alex-sherwin** [comment] 2017-09-30 19:56
Not sure why this is closed as invalid?  This is pretty easy to replicate and clear to check in the code what is happening.  The implementation claims to authenticate a user when it does no such thing

**Comment by rwinch** [comment] 2017-10-06 19:36
@alex-sherwin @espenhw Thank you for the additional feedback. This is now merged into master.

Please see my follow up comments on the PR.

**Comment by mschneid** [comment] 2019-02-07 14:15
Since Java 9 this workaround is no longer necessary. Even worse, it leads to a memory leak and an open socket. Since Java 9, every call to `LdapContext#reconnect(Control[])` initiates a new `LdapClient` without calling `LdapClient#close(Control[], boolean)` before. This leads to the situation that the former `LdapClient` remains alive and is never garbage collected because of the worker thread of the LDAP connection.

**Comment by rwinch** [comment] 2019-02-07 15:25
@mschneid This issue is closed. Can you please create a new issue with details and a minimal but complete sample to reproduce?
