### ISSUE TITLE
Newbie trying to build spring-ldap

### ISSUE THREAD

**Issue by kanondev7** [spring-projects/spring-ldap#495] opened 2018-11-07 22:42 UTC
...and I'm not familiar with gradle.  Using the newest source code, the build (./gradlew build) fails with:
FAILURE: Build failed with an exception.

* Where:
Script '/Users/ksc/Documents/workspace/spring-ldap/core/javacc.gradle' line: 11

* What went wrong:
Execution failed for task ':spring-ldap-core:downloadJavacc'.
> sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

What I am really trying to do is update an older version (2.0.1).  When I run that build, I get:
FAILURE: Build failed with an exception.

* What went wrong:
Cannot expand TAR '/Users/ksc/Documents/workspace/spring-ldap-2.0.1.RELEASE/core/build/javacc/javacc-5.0.tar.gz'.
It appears that the tar file is getting overwritten

**Comment by rwinch** [comment] 2018-11-07 22:48
Is there a reason you need to build it? Second, what is the output of `./gradlew --info`?

**Comment by kanondev7** [comment] 2018-11-07 23:18
I downloaded the source for 2.0.1 (I know it's old, but it does not have the bug I'm trying to avoid). 

The output of `./gradlew --info` is BUILD SUCCESSFUL:
`Starting Build
Starting file lock listener thread.
Settings evaluated using settings file '/Users/ksc/Documents/workspace/spring-ldap-2.0.1.RELEASE/settings.gradle'.
Projects loaded. Root project using build file '/Users/ksc/Documents/workspace/spring-ldap-2.0.1.RELEASE/build.gradle'.
Included projects: [root project 'spring-ldap', project ':spring-ldap-core', project ':spring-ldap-core-tiger', project ':spring-ldap-integration-tests', project ':spring-ldap-integration-tests-ad', project ':spring-ldap-integration-tests-openldap', project ':spring-ldap-integration-tests-spring20', project ':spring-ldap-integration-tests-spring25', project ':spring-ldap-integration-tests-spring30', project ':spring-ldap-integration-tests-sunone', project ':spring-ldap-ldif-batch', project ':spring-ldap-ldif-core', project ':spring-ldap-odm', project ':spring-ldap-odm-sample', project ':spring-ldap-plain-sample', project ':spring-ldap-sandbox', project ':spring-ldap-test', project ':spring-ldap-user-admin-sample']
Evaluating root project 'spring-ldap' using build file '/Users/ksc/Documents/workspace/spring-ldap-2.0.1.RELEASE/build.gradle'.
The ConfigurationContainer.add() method has been deprecated and is scheduled to be removed in Gradle 2.0. Please use the create() method instead.
The Test.testResultsDir property has been deprecated and is scheduled to be removed in Gradle 2.0. Please use the Test.getReports().getJunitXml().setDestination() property instead.
The Test.testReportDir property has been deprecated and is scheduled to be removed in Gradle 2.0. Please use the Test.getReports().getHtml().getDestination() property instead.
Evaluating project ':spring-ldap-core' using build file '/Users/ksc/Documents/workspace/spring-ldap-2.0.1.RELEASE/core/build.gradle'.
Evaluating project ':spring-ldap-core-tiger' using build file '/Users/ksc/Documents/workspace/spring-ldap-2.0.1.RELEASE/core-tiger/build.gradle'.
Evaluating project ':spring-ldap-integration-tests' using build file '/Users/ksc/Documents/workspace/spring-ldap-2.0.1.RELEASE/test/integration-tests/build.gradle'.
Evaluating project ':spring-ldap-test' using build file '/Users/ksc/Documents/workspace/spring-ldap-2.0.1.RELEASE/test-support/build.gradle'.
Evaluating project ':spring-ldap-integration-tests-ad' using build file '/Users/ksc/Documents/workspace/spring-ldap-2.0.1.RELEASE/test/integration-tests-ad/build.gradle'.
Evaluating project ':spring-ldap-integration-tests-openldap' using build file '/Users/ksc/Documents/workspace/spring-ldap-2.0.1.RELEASE/test/integration-tests-openldap/build.gradle'.
Evaluating project ':spring-ldap-integration-tests-spring20' using build file '/Users/ksc/Documents/workspace/spring-ldap-2.0.1.RELEASE/test/integration-tests-spring20/build.gradle'.
Evaluating project ':spring-ldap-integration-tests-spring25' using build file '/Users/ksc/Documents/workspace/spring-ldap-2.0.1.RELEASE/test/integration-tests-spring25/build.gradle'.
Evaluating project ':spring-ldap-integration-tests-spring30' using build file '/Users/ksc/Documents/workspace/spring-ldap-2.0.1.RELEASE/test/integration-tests-spring30/build.gradle'.
Evaluating project ':spring-ldap-integration-tests-sunone' using build file '/Users/ksc/Documents/workspace/spring-ldap-2.0.1.RELEASE/test/integration-tests-sunone/build.gradle'.
Evaluating project ':spring-ldap-ldif-batch' using build file '/Users/ksc/Documents/workspace/spring-ldap-2.0.1.RELEASE/ldif/ldif-batch/build.gradle'.
Evaluating project ':spring-ldap-ldif-core' using build file '/Users/ksc/Documents/workspace/spring-ldap-2.0.1.RELEASE/ldif/ldif-core/build.gradle'.
Evaluating project ':spring-ldap-odm' using build file '/Users/ksc/Documents/workspace/spring-ldap-2.0.1.RELEASE/odm/build.gradle'.
Evaluating project ':spring-ldap-odm-sample' using build file '/Users/ksc/Documents/workspace/spring-ldap-2.0.1.RELEASE/samples/odm/build.gradle'.
Evaluating project ':spring-ldap-plain-sample' using build file '/Users/ksc/Documents/workspace/spring-ldap-2.0.1.RELEASE/samples/plain/build.gradle'.
Evaluating project ':spring-ldap-sandbox' using build file '/Users/ksc/Documents/workspace/spring-ldap-2.0.1.RELEASE/sandbox/build.gradle'.
Evaluating project ':spring-ldap-user-admin-sample' using build file '/Users/ksc/Documents/workspace/spring-ldap-2.0.1.RELEASE/samples/user-admin/build.gradle'.
All projects evaluated.
No tasks specified. Using default task 'help'
Selected primary task 'help'
Tasks to be executed: [task ':help']
:help (Thread[main,5,main] - start
:help
Executing task ':help' due to:
  Task has not declared any outputs.

Welcome to Gradle 1.7-rc-1.

To run a build, run gradlew <task> ...

To see a list of available tasks, run gradlew tasks

To see a list of command-line options, run gradlew --help
:help (Thread[main,5,main]) - complete
Task worker [Thread[main,5,main]] finished, busy: 0.005 secs, idle: 0.005 secs, waited for cache: 0.0 secs

BUILD SUCCESSFUL

Total time: 4.774 secs
`

The output of `git --no-pager log -n 1` is "not a git repository".

**Comment by kanondev7** [comment] 2018-11-08 00:14
I worked around the issue with the compiler by manually installing javacc-5.0, removing task downloadJavacc and installJavacc, and replacing `task javacc() {
	ext.javaccHome = file("$buildDir/javacc/")
    ext.srcFile = file("src/main/javacc/DnParserImpl.jj")
    ext.srcDestDir = file("$buildDir/generated-src/javacc")
    ext.destDir = file("$srcDestDir/org/springframework/ldap/core")
    ext.homeDir = file("${javaccHome.path}/javacc-5.0")`

Now :api does not build

**Comment by kanondev7** [comment] 2018-11-08 02:52
In case anyone cares, solution for task :api with java8 is here: https://blog.joda.org/2014/02/turning-off-doclint-in-jdk-8-javadoc.html

**Comment by rwinch** [comment] 2018-11-08 16:03
@kanondev7 Thanks for the details. What is the bug you are trying to avoid? Has it been reported and fixed in a newer version?

**Comment by erdbeerschnitzel** [comment] 2019-03-05 20:28
The initial problem here was

> Execution failed for task ':spring-ldap-core:downloadJavacc'.
> 
> sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

This seems to happen if the gradle installation can't access the ca-certificates and therefore can't find a valid certificate for the URL https://javacc.org

The result is that gradle can't download javacc and the build fails.

Another workaround for the problem is to manually download javacc (http://javacc.org/downloads/javacc-5.0.tar.gz) and put it in the root of the project folder and then edit the javacc.gradle:

- remove the complete "task downloadJavacc"
- replace the first 2 lines of "task installJavacc" from

```
task installJavacc(type:Copy,dependsOn:downloadJavacc) {
    ext.archive = downloadJavacc.dest
```

to

```
task installJavacc(type:Copy) {
    ext.archive = file("/javacc-5.0.tar.gz")
```

Some solutions for the underlying problem can be found here: https://stackoverflow.com/questions/29584328/gradlew-bat-and-gradlew-sslhandshakeexception

**Comment by jzheaux** [comment] 2021-12-14 22:46
Spring LDAP 2.0.1 is quite old at this point and is no longer supported, so I'm going to close this ticket. It also appears that an appropriate workaround has been found anyway.

**Closed by jzheaux** 2021-12-14 22:46 UTC
