### ISSUE TITLE
Ldap over SSL issue in native image

### ISSUE THREAD

**Issue by kartik-kaushik** [spring-projects/spring-ldap#724] opened 2023-01-25 17:33 UTC
Describe the bug
 Spring Boot 3 native image not working with spring-ldap over ssl

Sample
Via the Spring Initializer, create any project with:

spring-boot-starter-parent:3.0.2
spring-boot-starter-data-ldap
spring-boot-starter-actuator

Application.properties
spring.ldap.urls=ldaps://localhost:636
spring.ldap.base=ou=people,dc=admin,dc=com
spring.ldap.username=cn=admin,ou=service_accounts,dc=com
spring.ldap.password=password
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=*

Check with actuator health endpoint. The application works normally, but with native image giving error:

Caused by: javax.naming.CommunicationException: localhost:636
        at java.naming@17.0.5/com.sun.jndi.ldap.Connection.<init>(Connection.java:253) ~[na:na]
        at java.naming@17.0.5/com.sun.jndi.ldap.LdapClient.<init>(LdapClient.java:137) ~[na:na]
        at java.naming@17.0.5/com.sun.jndi.ldap.LdapClient.getInstance(LdapClient.java:1616) ~[na:na]
        at java.naming@17.0.5/com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2848) ~[na:na]
        at java.naming@17.0.5/com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:348) ~[na:na]
        at java.naming@17.0.5/com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxFromUrl(LdapCtxFactory.java:225) ~[spring-ldaps:na]
        at java.naming@17.0.5/com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:189) ~[spring-ldaps:na]
        at java.naming@17.0.5/com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:243) ~[spring-ldaps:na]
        at java.naming@17.0.5/com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:154) ~[spring-ldaps:na]
        at java.naming@17.0.5/com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:84) ~[spring-ldaps:na]
        at java.naming@17.0.5/javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:732) ~[spring-ldaps:na]
        at java.naming@17.0.5/javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305) ~[spring-ldaps:na]
        at java.naming@17.0.5/javax.naming.InitialContext.init(InitialContext.java:236) ~[spring-ldaps:na]
        at java.naming@17.0.5/javax.naming.ldap.InitialLdapContext.<init>(InitialLdapContext.java:154) ~[na:na]
        at org.springframework.ldap.core.support.LdapContextSource.getDirContextInstance(LdapContextSource.java:42) ~[spring-ldaps:3.0.0]
        at org.springframework.ldap.core.support.AbstractContextSource.createContext(AbstractContextSource.java:351) ~[spring-ldaps:3.0.0]
        ... 75 common frames omitted
Caused by: java.lang.NoSuchMethodException: javax.net.ssl.SSLSocketFactory.getDefault()
        at java.base@17.0.5/java.lang.Class.getMethod(DynamicHub.java:2227) ~[spring-ldaps:na]
        at java.naming@17.0.5/com.sun.jndi.ldap.Connection.createSocket(Connection.java:293) ~[na:na]
        at java.naming@17.0.5/com.sun.jndi.ldap.Connection.<init>(Connection.java:232) ~[na:na]
        ... 90 common frames omitted

Kindly help in resolution of the same. If not supported, is there any alternative or work around for now?

**Comment by kartik-kaushik** [comment] 2023-01-30 17:19
Any update on it or tentative date or workaround?

**Comment by jzheaux** [comment] 2023-02-07 20:39
This appears to be a duplicate of #723. Have you already tried the workaround there?

**Comment by jzheaux** [comment] 2023-04-18 16:32
I'm closing this due to lack of activity. If there is more to discuss, we can re-open at that time.

**Closed by jzheaux** 2023-04-18 16:32 UTC
Labels: status: duplicate, status: waiting-for-feedback, type: bug, in: core
